# total keys amount among all databases
UserParameter=redis.keys,redis-cli${REDIS_PASS:+ -a "${REDIS_PASS}"} info |grep -E -o 'keys=[0-9]+' |awk -F= '{sum += $2} END {print sum}'

# info statistics
UserParameter=redis.stat[*],redis-cli${REDIS_PASS:+ -a "${REDIS_PASS}"} info |grep -w $1 |cut -d: -f2

# get raw data from redis
UserParameter=redis.raw[*],redis-cli${REDIS_PASS:+ -a "${REDIS_PASS}"} --raw $1 $2
UserParameter=redis.discovery[*],/etc/zabbix/zabbix_agentd.conf.d/scripts/redis-discovery.sh $1 $2
