#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service 10-redis

SERVICE_NAME="redis"
check_container_initialized
check_service_initialized init

transform_var file REDIS_PASS
redis_build_runtime_arguments

liftoff

print_start "Starting Redis $(grep -o "ADD: Redis .* |" /container/build/${IMAGE_NAME/\//_}/build.log | awk '{print $3}')"
exec s6-setuidgid redis redis-server --dir "${DATA_PATH}" \
                                     ${REDIS_PASS:+--requirepass $REDIS_PASS} \
                                     --loglevel "${LOG_LEVEL}" \
                                     --port ${REDIS_PORT} \
				     				${redis_persistence} ${redis_logs} ${redis_socket}
