services:

  redis-app:
    image: docker.io/nfrastack/redis:8
    container_name: redis-app
    volumes:
    #- ./data:/data
    #- ./logs:/logs
    environment:
    - CONTAINER_NAME=redis-app

    - REDIS_PASS=password
    networks:
    - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true

